const token=document.querySelector('meta[name=local-token]').content;
const message=document.querySelector('#message');let selected;
async function api(path,data){const r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:{authorization:'Bearer '+token,...(data?{'content-type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});const out=await r.json();if(!r.ok)throw Error(out.error);return out;}
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n;}
async function action(button,fn){button.disabled=true;message.textContent='';try{await fn();await refresh();}catch(e){message.textContent=e.message;}finally{button.disabled=false;}}
async function qr(){const out=await api('qr',{id:selected.project.id,service:selected.service.name,page:document.querySelector('#qr-page').value});document.querySelector('#qr-image').src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(out.svg);document.querySelector('#qr-url').textContent=out.url;}
async function refresh(){try{const state=await api('status');document.querySelector('#running').textContent=state.projects.filter(p=>p.status==='running').length;document.querySelector('#projects').textContent=state.projects.length;document.querySelector('#namespace').textContent=state.namespace;const cards=document.querySelector('#cards');cards.replaceChildren();if(!state.projects.length)cards.append(el('div','card empty','No projects yet. Run local-dev setup in a worktree, then refresh.'));
for(const p of state.projects){const card=el('article','card');const head=el('div','card-head');const title=el('div');title.append(el('h3','',p.name),el('div','project',p.project||p.file));head.append(title,el('span','badge '+(p.status==='running'?'running':''),p.status));card.append(head);const services=el('div','services');
for(const s of p.services){const row=el('div','service');const label=el('div','service-name',s.name);label.append(el('span','adapter',s.adapter+' · :'+s.port));const identity=el('div','identity');const link=el('a','',s.origin);link.href=s.origin+(s.adapter==='simulator'?'/simulator/':s.adapter==='app'&&p.profile!=='integration'?'/pins.html':'/');link.target='_blank';link.rel='noreferrer';identity.append(link,el('div','branch',s.identity.branch+' · '+(s.identity.commit||'uncommitted').slice(0,9)+(s.identity.dirty?' · modified':'')));const share=el('button','button','QR ↗');share.addEventListener('click',()=>action(share,async()=>{selected={project:p,service:s};document.querySelector('#qr-page').value=new URL(link.href).pathname;await qr();document.querySelector('#qr-dialog').showModal();}));row.append(label,identity,share);services.append(row);}card.append(services);
if(p.id){const controls=el('div','controls');const profile=el('select');profile.setAttribute('aria-label','Profile for '+p.name);for(const [value,label] of [['visual','Visual'],['integration','Integration'],['simulator-source','Simulator source']]){const option=el('option','',label);option.value=value;profile.append(option);}profile.value=p.profile;const button=el('button','button '+(p.status==='stopped'?'primary':''),p.status==='running'?'Stop stack':p.status==='stopped'?'Start stack':'Check status');button.disabled=!['running','stopped'].includes(p.status);button.addEventListener('click',()=>action(button,()=>api(p.status==='running'?'stop':'start',{id:p.id,profile:profile.value})));controls.append(profile,button,el('span','path',p.file));card.append(controls);}cards.append(card);}}catch(e){message.textContent=e.message;}}
document.querySelector('#refresh').addEventListener('click',refresh);document.querySelector('#qr-close').addEventListener('click',()=>document.querySelector('#qr-dialog').close());document.querySelector('#qr-form').addEventListener('submit',e=>{e.preventDefault();qr().catch(e=>message.textContent=e.message);});refresh();setInterval(()=>{if(!document.querySelector('#qr-dialog').open && !['SELECT','INPUT'].includes(document.activeElement?.tagName))refresh();},5000);
